server:
  port: 9999

spring:
  application:
    name: gateWay-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心自动路由功能,
      routes: #路由
       - id: nacos-provider #没有固定要求, 路由id, 但是要保证唯一. 建议配合服务名
         uri: lb://nacos-provider
         predicates: #断言
           - Path=/hx/** #路径相匹配进行路由
